# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_areacode', models.CharField(choices=[('+61', '+61')], default='+61', max_length=5)),
                ('receiver_number', models.IntegerField()),
                ('sender_areacode', models.CharField(choices=[('+61', '+61')], default='+61', max_length=5)),
                ('sender_number', models.IntegerField()),
                ('scheduled_time', models.DateTimeField()),
                ('content', models.TextField(max_length=130)),
                ('cancellation_code', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
